<?xml version="1.0" ?>
<robot name="tether_2m" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="cable_radius"     value="0.0031" />
  <xacro:property name="cable_mass"       value="0.02" />
  <xacro:property name="cable_length"     value="2.421" />
  <xacro:property name="num_elements"     value="29" />
  <xacro:property name="elem_length_ends" value="0.0001" />
  <xacro:property name="elem_mass_ends"   value="0.0001" />

  <!-- Joint properties -->
  <xacro:property name="joint_friction" value="0" />
  <xacro:property name="joint_damping"  value="0.005"  />
  <!-- <xacro:property name="joint_effort"   value="1000" />
  <xacro:property name="joint_velocity" value="1000" /> -->

  <!-- Derived values -->
  <xacro:property name="elem_mass_main"   value="${cable_mass/num_elements}" />
  <xacro:property name="elem_length_main" value="${cable_length/num_elements}" />

  <!-- Legacy placeholders kept for template compatibility -->
  <xacro:property name="ang_e" value="${pi/num_elements}"/>
  <xacro:property name="ang_i" value="${pi - ang_e}"/>
  <xacro:property name="dist_connect_points" value="${elem_length_main/sin(pi/(2*num_elements))}"/>

  <!-- Link macro -->
  <xacro:macro name="cable_element" params="elem_name elem_length elem_mass">
    <link name="${elem_name}">
      <inertial>
        <origin xyz="0 0 ${elem_length/2}" rpy="0 0 0"/>
        <mass value="${elem_mass}"/>
        <inertia
          ixx="${(1.0/12.0)*elem_mass*(3*cable_radius*cable_radius + elem_length*elem_length)}"
          ixy="0" ixz="0"
          iyy="${(1.0/12.0)*elem_mass*(3*cable_radius*cable_radius + elem_length*elem_length)}"
          iyz="0"
          izz="${0.5*elem_mass*(cable_radius*cable_radius)}"/>
      </inertial>

      <visual>
        <origin xyz="0 0 ${elem_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${elem_length}" radius="0.0031"/>
        </geometry>
      </visual>

      <!-- <collision>
        <origin xyz="0 0 ${elem_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${elem_length}" radius="0.0031"/>
        </geometry>
      </collision> -->
    </link>
  </xacro:macro>

  <!-- Recursive chain -->
  <xacro:macro name="generate_cable" params="elem_num">
    <xacro:cable_element elem_name="element_${elem_num}"
                         elem_length="${elem_length_main}"
                         elem_mass="${elem_mass_main}"/>

    <xacro:if value="${elem_num-1}">
      <xacro:generate_cable elem_num="${elem_num-1}" />
    </xacro:if>

    <xacro:if value="${elem_num-1 > 0}">
      <joint name="joint_${elem_num-1}_to_${elem_num}" type="continuous">
        <axis xyz="0 1 0">
          <!-- <limit effort="${joint_effort}" velocity="${joint_velocity}"/> -->
          <dynamics damping="0.005" friction="0"/>
        </axis>
        <origin xyz="0 0 ${elem_length_main}" rpy="0 0 0"/>
        <parent link="element_${elem_num-1}"/>
        <child  link="element_${elem_num}"/>
      </joint>
    </xacro:if>
  </xacro:macro>

  <!-- Interior chain -->
  <xacro:generate_cable elem_num="29" />

  <!-- Endcaps -->
  <xacro:cable_element elem_name="element_first"
                       elem_length="0.0001"
                       elem_mass="0.0001"/>
  <xacro:cable_element elem_name="element_last"
                       elem_length="0.0001"
                       elem_mass="0.0001"/>

  <!-- First to element_1 -->
  <joint name="joint_0_to_1" type="continuous">
    <axis xyz="0 1 0">
      <!-- <limit effort="${joint_effort}" velocity="${joint_velocity}"/> -->
      <dynamics damping="0.005" friction="0"/>
    </axis>
    <origin xyz="0 0 0.0001" rpy="0 0 0"/>
    <parent link="element_first"/>
    <child  link="element_1"/>
  </joint>

  <!-- Last interior to endcap -->
  <joint name="joint_29_to_${num_elements+1}" type="continuous">
    <axis xyz="0 1 0">
      <!-- <limit effort="${joint_effort}" velocity="${joint_velocity}"/> -->
      <dynamics damping="0.005" friction="0"/>
    </axis>
    <origin xyz="0 0 ${elem_length_main}" rpy="0 0 0"/>
    <parent link="element_29"/>
    <child  link="element_last"/>
  </joint>

</robot>
