<?xml version="1.0" ?>
<robot name="tether" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Xacro to generate tether SDF -->
    <!-- Note: need to manually find and replace all references to 'revolute'
    with 'universal' in final SDF to get better tether. This also involves adding in a second axis.
    These changes are now all defined in generate_sdf.sh-->

    <!-- Define properties -->
    <xacro:property name="dist_connect_points" value="1.4" /> <!--1.42-->
    <xacro:property name="tether_radius" value="0.01" />
    <xacro:property name="tether_mass" value="0.02" /> <!--0.1-->
    <xacro:property name="num_elements" value="1" /> <!--5-->

    <xacro:property name="elem_length_ends" value="0.0001" />
    <xacro:property name="elem_mass_main" value="${tether_mass/num_elements}" />
    <xacro:property name="elem_mass_ends" value="0.0001" />

    <xacro:property name="joint_friction" value="0" />
    <xacro:property name="joint_damping" value="0.01" />

    <!-- Calculations -->
    <xacro:property name="elem_length_main" value="${(((dist_connect_points**2)/2)*(1-cos(ang_e)))**0.5}"/>
    <xacro:property name="ang_e" value="${pi/num_elements}"/>
    <xacro:property name="ang_i" value="${pi - ang_e}"/>


    <!-- Define link macro -->
    <xacro:macro name="tether_element" params="elem_name elem_length elem_mass">
        <link name="${elem_name}">
            <inertial>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <mass value="${elem_mass}"/>
                <inertia ixx="${1/12*elem_mass*(3*tether_radius**2 + elem_length**2)}" ixy="0" ixz="0" iyy="${1/12*elem_mass*(3*tether_radius**2 + elem_length**2)}" iyz="0" izz="${1/2*elem_mass*(tether_radius**2)}" />
            </inertial>
            <visual>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="${tether_radius}"/>
                </geometry>
            </visual>
            <!-- <collision>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="${tether_radius}"/> 0.0001
                </geometry>
            </collision> -->
        </link>
    </xacro:macro>


    <!-- Recursive loop to generate multiple elements and joints for said elements -->
    <xacro:macro name="generate_tether" params="elem_num">
        <!-- Generate elements and recurse-->
        <xacro:tether_element elem_name="element_${elem_num}" elem_length="${elem_length_main}" elem_mass="${elem_mass_main}" />

        <xacro:if value="${elem_num-1}">
            <xacro:generate_tether elem_num="${elem_num-1}" />
        </xacro:if>

        <!-- Define joints -->
        <xacro:if value="${elem_num-1 > 0}">
            <joint name="joint_${elem_num-1}_to_${elem_num}" type="continuous">
                <axis xyz="0. 1. 0."/>
                <!-- <axis xyz="0. 1. 1."/> -->

                <origin xyz="${elem_length_main} 0 0" rpy="0 ${-ang_e} 0"/>

                <!-- <xacro:if value="${elem_num  == 1}">
                    <origin xyz="${elem_length_main} 0 0" rpy="0 ${ang_i/2} 0"/>
                </xacro:if>
                <xacro:if value="${elem_num  == num_elements}">
                    <origin xyz="${elem_length_main} 0 0" rpy="0 ${(pi-ang_e)/2} 0"/>
                </xacro:if>
                <xacro:if value="${(elem_num > 1) and (elem_num < num_elements)}">
                    <origin xyz="${elem_length_main} 0 0" rpy="0 ${-ang_e} 0"/>
                </xacro:if> -->

                <parent link="element_${elem_num-1}"/>
                <child link="element_${elem_num}"/>

                <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
            </joint>

        </xacro:if>

    </xacro:macro>

    <!-- Call recursive loop to generate tether -->
    <xacro:generate_tether elem_num="${num_elements}" />

    <!-- Add start and end elements and joints-->
    <xacro:tether_element elem_name="element_first" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" />
    <xacro:tether_element elem_name="element_last" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" />

    <!-- Prismatic joints may or may not be useful. First is for tension modelling, second is for attempting to remove radial cable forces-->
    <xacro:tether_element elem_name="element_p1" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" />
    <xacro:tether_element elem_name="element_p2" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" />
    <xacro:tether_element elem_name="element_p3" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" />

    <!-- Load-side ball joint -->
    <joint name="joint_0_to_p1" type="continuous">
        <axis xyz="0. 1. 0."/>
        <origin xyz="${elem_length_ends} 0 0" rpy="0 ${ang_i/2} 0"/>
        <parent link="element_first"/>
        <child link="element_p1"/>
        <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>


    <!-- Prismatic joints (controlling tension direction) -->
    <joint name="joint_p1_to_p2" type="prismatic">
        <origin xyz="${elem_length_ends} 0 0" rpy="0 0 0"/>
        <parent link="element_p1"/>
        <child link="element_p2"/>
        <axis xyz="1. 0. 0."/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit lower="-1.0" upper="0.0" effort="10000.0" velocity="10000.0"/>
    </joint>

    <joint name="joint_p2_to_p3" type="prismatic">
        <origin xyz="${elem_length_ends} 0 0" rpy="0 0 0"/>
        <parent link="element_p2"/>
        <child link="element_p3"/>
        <axis xyz="0. 1. 0."/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit lower="-0.1" upper="0.1" effort="10000.0" velocity="10000.0"/>
    </joint>

    <joint name="joint_p3_to_1" type="prismatic">
        <origin xyz="${elem_length_ends} 0 0" rpy="0 0 0"/>
        <parent link="element_p3"/>
        <child link="element_1"/>
        <axis xyz="0. 0. 1."/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit lower="-0.1" upper="0.1" effort="10000.0" velocity="10000.0"/>
    </joint>


    <!-- Drone-side ball joint -->
    <joint name="joint_${num_elements}_to_${num_elements+1}" type="continuous">
        <axis xyz="0. 1. 0."/>
        <origin xyz="${elem_length_main} 0 0" rpy="0 ${(pi-ang_e)/2} 0"/>
        <parent link="element_${num_elements}"/>
        <child link="element_last"/>
        <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>

</robot>
