<?xml version="1.0" ?>
<robot name="tether_2m" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Xacro to generate cable SDF -->
    <!-- Note: need to manually find and replace all references to 'revolute'
    with 'universal' in final SDF to get better cable. This also involves adding in a second axis.
    These changes are now all defined in generate_sdf.sh-->

    <!-- Define properties -->
    <!-- <xacro:property name="dist_connect_points" value="1.5475" />  -->
    <xacro:property name="cable_radius" value="0.0031" />
    <xacro:property name="cable_mass" value="0.02" />
    <xacro:property name="cable_length" value="2.421" />
    <xacro:property name="num_elements" value="15" />
    <xacro:property name="elem_length_ends" value="0.0001" />
    <xacro:property name="elem_mass_ends" value="0.0001" />

    <!-- Joint properties -->
    <xacro:property name="joint_friction" value="0" />
    <xacro:property name="joint_damping" value="0.002" />

    <!-- Calculations -->
    <xacro:property name="elem_mass_main" value="${cable_mass/num_elements}" />

    <xacro:property name="ang_e" value="${pi/num_elements}"/>
    <xacro:property name="ang_i" value="${pi - ang_e}"/>
    <xacro:property name="elem_length_main" value="${cable_length/num_elements}"/>
    <xacro:property name="dist_connect_points" value="${elem_length_main/sin(pi/(2*num_elements))}"/>

    <!-- Define link macro -->
    <xacro:macro name="cable_element" params="elem_name elem_length elem_mass">
        <link name="${elem_name}">
            <inertial>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <mass value="${elem_mass}"/>
                <inertia ixx="${1/12*elem_mass*(3*cable_radius**2 + elem_length**2)}" ixy="0" ixz="0" iyy="${1/12*elem_mass*(3*cable_radius**2 + elem_length**2)}" iyz="0" izz="${1/2*elem_mass*(cable_radius**2)}" />
            </inertial>
            <visual>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="0.0031"/>
                </geometry>
            </visual>
            <!-- <collision>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="0.0031"/> 0.0001
                </geometry>
            </collision> -->
        </link>
    </xacro:macro>


    <!-- Recursive loop to generate multiple elements and joints for said elements -->
    <xacro:macro name="generate_cable" params="elem_num">
        <!-- Generate elements and recurse-->
        <xacro:cable_element elem_name="element_${elem_num}" elem_length="${elem_length_main}" elem_mass="${elem_mass_main}" />

        <xacro:if value="${elem_num-1}">
            <xacro:generate_cable elem_num="${elem_num-1}" />
        </xacro:if>

        <!-- Define joints -->
        <xacro:if value="${elem_num-1 > 0}">
            <joint name="joint_${elem_num-1}_to_${elem_num}" type="continuous">
                <axis xyz="0. 1. 0."/>
                <!-- <axis xyz="0. 1. 1."/> -->

                <origin xyz="${elem_length_main} 0 0" rpy="0 ${-ang_e} 0"/>

                <!-- <xacro:if value="${elem_num  == 1}">
                    <origin xyz="${elem_length_main} 0 0" rpy="0 ${ang_i/2} 0"/>
                </xacro:if>
                <xacro:if value="${elem_num  == num_elements}">
                    <origin xyz="${elem_length_main} 0 0" rpy="0 ${(pi-ang_e)/2} 0"/>
                </xacro:if>
                <xacro:if value="${(elem_num > 1) and (elem_num < num_elements)}">
                    <origin xyz="${elem_length_main} 0 0" rpy="0 ${-ang_e} 0"/>
                </xacro:if> -->

                <parent link="element_${elem_num-1}"/>
                <child link="element_${elem_num}"/>

                <dynamics damping="0.002" friction="0"/>
            </joint>

        </xacro:if>

    </xacro:macro>

    <!-- Call recursive loop to generate cable -->
    <xacro:generate_cable elem_num="15" />

    <!-- Add start and end elements and joints-->
    <xacro:cable_element elem_name="element_first" elem_length="0.0001" elem_mass="0.0001" />
    <xacro:cable_element elem_name="element_last" elem_length="0.0001" elem_mass="0.0001" />

    <joint name="joint_0_to_1" type="continuous">
        <axis xyz="0. 1. 0."/>
        <origin xyz="0.0001 0 0" rpy="0 ${ang_i/2} 0"/>
        <parent link="element_first"/>
        <child link="element_1"/>
        <dynamics damping="0.002" friction="0"/>
    </joint>
    <joint name="joint_15_to_${num_elements+1}" type="continuous">
        <axis xyz="0. 1. 0."/>
        <origin xyz="${elem_length_main} 0 0" rpy="0 ${(pi-ang_e)/2} 0"/>
        <parent link="element_15"/>
        <child link="element_last"/>
        <dynamics damping="0.002" friction="0"/>
    </joint>

</robot>
